# Generated by Django 3.2.16 on 2022-10-31 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediapp', '0004_bed'),
    ]

    operations = [
        migrations.AddField(
            model_name='bed',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
