# Generated by Django 3.2.16 on 2022-10-31 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mediapp', '0005_bed_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bed',
            name='status',
        ),
    ]
