# Generated by Django 3.2.16 on 2022-10-31 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediapp', '0007_bed_num_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='bed_num',
            name='patientId',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='bed_num',
            name='patientName',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
