# Generated by Django 3.2.16 on 2022-10-31 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediapp', '0008_auto_20221031_2224'),
    ]

    operations = [
        migrations.AddField(
            model_name='bed',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
