# Generated by Django 3.2.16 on 2022-10-31 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediapp', '0009_bed_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='bed',
            name='patientId',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='bed',
            name='patientName',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
