# Generated by Django 3.0.5 on 2022-11-01 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mediapp', '0011_auto_20221101_1043'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bed',
            name='patientId',
        ),
        migrations.RemoveField(
            model_name='bed',
            name='patientName',
        ),
        migrations.RemoveField(
            model_name='bed',
            name='status',
        ),
    ]
