# Generated by Django 3.0.5 on 2022-11-01 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediapp', '0013_oxygen'),
    ]

    operations = [
        migrations.AddField(
            model_name='bed',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
