# Generated by Django 3.0.5 on 2022-11-03 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediapp', '0017_med'),
    ]

    operations = [
        migrations.CreateModel(
            name='stafff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patientId', models.PositiveIntegerField(null=True)),
                ('patientName', models.CharField(max_length=40)),
                ('assignedDoctorName', models.CharField(max_length=40)),
                ('filename', models.CharField(max_length=40, null=True)),
                ('filee', models.FileField(upload_to='specs')),
            ],
        ),
    ]
