# Generated by Django 3.0.5 on 2022-11-03 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediapp', '0019_item_order_orderitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('T', 'Tablet'), ('L', 'Liquid')], max_length=2),
        ),
    ]
