# Generated by Django 3.0.5 on 2022-11-03 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediapp', '0020_auto_20221103_2312'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.ImageField(default=1, upload_to='images/'),
            preserve_default=False,
        ),
    ]
